// Global Constants

///  A "magic" number assigned to a reduce node's length
/// value to indicate that it is to use the symbol accumulator
/// to determine how many symbols are to removed from the
/// parse stack when the reduce function is called.
pub const IR_REDUCE_NUMERIC_LEN_ID: u32 = 0x90FA0102;

/// A postfix string added to names of production generated by left to
/// right recursive conversion.
pub const prime_symbol: &'static str = "_prime";
