#! /usr/bin/zsh

# The default parser for sherpa is the bytecode parse, which is not ideal
# for performance demanding builds. This script uses the base bytecode sherpa
# configuration to build a binary parser library that can then replace the 
# default bytecode parser.

pushd ${0:a:h}/..

ROOT_DIR=$PWD
SHERPA_LIBRARY_DIR=$ROOT_DIR/source/lib/sherpa-core/lib
SHERPA_CLI_DIR=$ROOT_DIR/source/app/cli

pushd $SHERPA_CLI_DIR

cargo run \
    --bin sherpa \
    -Z package-features \
    --features "sherpa_core/llvm" \
    -- build -t llvm\
     -a \
     -l rust \
     --libout $ROOT_DIR/source/lib/sherpa-core/lib/ \
     -o $ROOT_DIR/source/lib/sherpa-core/grammar/compile/parser/ \
      $ROOT_DIR/source/grammar/v1_0_0/grammar.sg