#! /usr/bin/env zsh

# The default parser for radlr is the bytecode parse, which is not ideal
# for demanding builds. This script uses the bytecode radlr
# configuration to build a binary parser library that can then replace the 
# default bytecode parser.

pushd ${0:a:h}/..

ROOT_DIR=$PWD
RADLR_CRATES_DIR=$ROOT_DIR/crates/radlr-core/lib
RADLR_CLI_DIR=$ROOT_DIR/src/app/cli

pushd $RADLR_CLI_DIR

cargo run \
    --bin radlr \
    --release \
    --features "radlr-cli/llvm" \
    -- build -t llvm\
    --name radlr \
     -a \
     -l rust \
     --libout $ROOT_DIR/crates/radlr-core/lib/ \
     -o $ROOT_DIR/crates/radlr-core/parser/ \
      $ROOT_DIR/grammars/radlr/2.0.0/grammar.sg
