#! /bin/zsh

# The default parser for sherpa is the bytecode parse, which is not ideal
# for demanding builds. This script uses the bytecode sherpa
# configuration to build a binary parser library that can then replace the 
# default bytecode parser.

pushd ${0:a:h}/..

ROOT_DIR=$PWD
SHERPA_LIBRARY_DIR=$ROOT_DIR/src/lib/sherpa-core/lib
SHERPA_CLI_DIR=$ROOT_DIR/src/app/cli

pushd $SHERPA_CLI_DIR

cargo run \
    --bin sherpa \
    --release \
    --features "sherpa-cli/llvm" \
    -- build -t llvm\
    --name sherpa \
     -a \
     -l rust \
     --libout $ROOT_DIR/src/lib/sherpa-core/lib/ \
     -o $ROOT_DIR/src/lib/sherpa-core/parser/ \
      $ROOT_DIR/src/grammar/sherpa/2.0.0/grammar.sg
