#! /usr/bin/zsh

# Move to project root
pushd .
pushd ${0:a:h}/..

# CONFIGURE DIRECTORIES
ROOT_DIR=$PWD
SHERPA_LIB_DIR=$SITE_OUT_DIR/src/sherpa
TARGET_DIR=$ROOT_DIR/target
SHERPA_LAB_SRC_DIR=$ROOT_DIR/source/web/lab/src/sherpa
SHERPA_LAB_PUB_DIR=$ROOT_DIR/source/web/lab/public
mkdir -p $SHERPA_LIB_DIR

# Navigate to sherpa-wasm
pushd $PWD/source/web/sherpa-wasm

# Build the wasm library
# wasm-pack build --dev --target web
wasm-pack build --no-typescript --target web

# Move the wasm data to out lab directory
mkdir -p $SHERPA_LAB_SRC_DIR
mkdir -p $SHERPA_LAB_PUB_DIR
cp ./pkg/* $SHERPA_LAB_SRC_DIR
cp $SHERPA_LAB_SRC_DIR/sherpa_wasm_bg.wasm $SHERPA_LAB_PUB_DIR/

# Create a public folder for output

# Copy the WASM module to public folder
#cargo build --package sherpa-wasm --target=wasm32-unknown-unknown

# Move the wasm data to out die
# cp $TARGET_DIR/wasm32-unknown-unknown/debug/sherpa_wasm.wasm $SHERPA_LIB_DIR


# Move to root
popd 
# Move to to script folder
popd
