#! /usr/bin/env zsh

pushd ${0:a:h}/..

# Build the radlr release for linux
cargo build --package radlr-cli --release --bin radlr 

# Output the build to the releases folder.
mkdir -p releases/linux/bin

mv ./target/release/radlr ./releases/linux/bin/radlr
