#! /bin/zsh

# This script is used to rebuild the base sherpa bytecode parser
# This should only ever need to be done if:
# 1. The sherpa grammar is extended or modified
# 2. New features are added to bytecode parsers that need to 
#    be incorporated into the sherpa grammar parser.

pushd ${0:a:h}/..

ROOT_DIR=$PWD
SHERPA_LIBRARY_DIR=$ROOT_DIR/src/lib/sherpa-core/lib
SHERPA_CLI_DIR=$ROOT_DIR/src/app/cli
export RUSTFLAGS="-Awarnings"
pushd $SHERPA_CLI_DIR

cargo run \
    --bin sherpa \
    -- build -t bytecode\
     -a \
     -d \
     -l rust \
     --libout $ROOT_DIR/src/lib/sherpa-core/lib/ \
     -o $ROOT_DIR/src/lib/sherpa-formatter/parser/ \
      $ROOT_DIR/src/grammar/sherpa/2.0.0/ascript_form.sg
