#! /usr/bin/zsh

# Move to project root
pushd .
pushd ${0:a:h}/..

##########################
# Setup environment variables
# this should always be sourced from the root directory
. ./scripts/env_vars
##########################


##########################
# Setup directories 
echo "CLEAR_PUBLIC_FOLDER"

rm -rf $WEB_FOLDER
##########################


##########################
## SHERPA DOC
pushd $SHERPA_DOC_DIR

# remove old public dir
rm -rf $SHERPA_DOC_PUB_DIR

# build files
hugo

# link the public folder to repo public
ln -s $SHERPA_DOC_PUB_DIR $WEB_FOLDER

popd
##########################


##########################
## SHERPA WASM
$ROOT_DIR/scripts/build_wasm dev
##########################


##########################
## SHERPA LAB
pushd $SHERPA_LAB_DIR

# build files
npm run build

# remove the old lab folder
rm $WEB_FOLDER/lab

# link public folder to public/lab
ln -s $SHERPA_LAB_PUB_DIR $WEB_FOLDER/lab

popd
##########################


##########################
## Startup dev environment
./scripts/run_dev_server
##########################

popd
popd
echo "DONE"
