#! /bin/zsh

# Move to project root
pushd .
pushd ${0:a:h}/..

##########################
# Setup environment variables
# this should always be sourced from the root directory
. ./scripts/env_vars
##########################


##########################
# Setup directories 
echo "CLEAR_PUBLIC_FOLDER"

rm -rf $PUBLIC_WEB_FOLDER
##########################


##########################
## SHERPA WASM
$ROOT_DIR/scripts/build_wasm dev
##########################


##########################
## SHERPA DOC
pushd $SHERPA_WEB_SOURCE_DIR

# remove old public dir
rm -rf $SHERPA_DOC_PUB_DIR

# build files
hugo

# link the public folder to repo public
ln -s $SHERPA_DOC_PUB_DIR $PUBLIC_WEB_FOLDER

popd
##########################

##########################
## Startup dev environment
./scripts/run_dev_server
##########################

popd
popd
echo "DONE"
