#! /bin/zsh

# The default parser for radlr is the bytecode parse, which is not ideal
# for performance demanding builds. This script uses the base bytecode radlr
# configuration to build a binary parser library that can then replace the 
# default bytecode parser.

pushd ${0:a:h}/..

ROOT_DIR=$PWD
RADLR_LIBRARY_DIR=$ROOT_DIR/src/lib
RADLR_CLI_DIR=$ROOT_DIR/src/app/cli

pushd $RADLR_LIBRARY_DIR

cargo test --workspace --features "radlr_core/binary-parser"

pushd $RADLR_CLI_DIR

cargo test --features "radlr_core/binary-parser"