#! /usr/bin/env zsh

# The default parser for radlr is the bytecode parse, which is not ideal
# for performance demanding builds. This script uses the base bytecode radlr
# configuration to build a binary parser library that can then replace the 
# default bytecode parser.

pushd ${0:a:h}/..

ROOT_DIR=$PWD
RADLR_CRATES_DIR=$ROOT_DIR/crates
RADLR_CLI_DIR=$ROOT_DIR/src/app/cli

pushd $RADLR_CRATES_DIR

cargo test --workspace

pushd $RADLR_CLI_DIR

cargo test --release