#! /usr/zsh

# The default parser for sherpa is the bytecode parse, which is not ideal
# for performance demanding builds. This script uses the base bytecode sherpa
# configuration to build a binary parser library that can then replace the 
# default bytecode parser.

pushd ${0:a:h}/..

ROOT_DIR=$PWD
SHERPA_LIBRARY_DIR=$ROOT_DIR/src/lib
SHERPA_CLI_DIR=$ROOT_DIR/src/app/cli

pushd $SHERPA_LIBRARY_DIR

cargo test --workspace