#! /usr/zsh

# Move to project root
pushd .
pushd ${0:a:h}/..

##########################
# Setup environment variables
# this should always be sourced from the root directory
. ./scripts/env_vars
##########################


##########################
## Startup dev environment
pushd $SHERPA_WEB_SOURCE_DIR
echo $PWD
hugo version
hugo server --disableFastRender

popd
##########################

popd
popd
echo "DONE"
